### ISSUE TITLE
video.title.runs.at is not a function

### ISSUE THREAD

**Issue by flaviotordini** [FreeTubeApp/yt-channel-info#117]
I'm getting this running on nodejs.

TypeError: video.title.runs.at is not a function
    at YoutubeGrabberHelper.parseVideo ([...]node_modules/yt-channel-info/app/helper.js:192:49)
    at [...]node_modules/yt-channel-info/app/helper.js:110:19

**Comment by ChunkyProgrammer** [comment]
what channel id are you using?

**Comment by flaviotordini** [comment]
UCmL8_HK_O5necMoKxkw4K6Q but it's happening on many others for me

**Comment by ChunkyProgrammer** [comment]
You might need to add a pollyfill for the at function (or use a newer version of EcmaScript). 
https://github.com/tc39/proposal-relative-indexing-method#polyfill

It looks like the 'at' function was only introduced in node version 16.6.0 so updating node might also fix the issue
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility

**Comment by flaviotordini** [comment]
Oh I see. Is the .at() usage really needed? Is it called with negative indexes? Otherwise it could be replaced with the bracket notation.

**Comment by flaviotordini** [comment]
I just created PR #119
