### ISSUE TITLE
Support new YouTube url @

### ISSUE THREAD

**Issue by tanmanh0707** [FreeTubeApp/yt-channel-info#129]
Youtube has new url format 
youtube.com/@channelname
Is it possible to support this url?
Thank you.

**Comment by krishtam-dev** [comment]
> Youtube has new url format youtube.com/@channelname Is it possible to support this url? Thank you.

is it fixed ?

**Comment by tanmanh0707** [comment]
> > Youtube has new url format youtube.com/@channelname Is it possible to support this url? Thank you.
> 
> is it fixed ?

Yes, pull request [#128](https://github.com/FreeTubeApp/yt-channel-info/pull/128) has been merged

**Comment by krishtam-dev** [comment]
Please give me something to contact you

**Comment by krishtam-dev** [comment]
> > > Youtube has new url format youtube.com/@channelname Is it possible to support this url? Thank you.
> > 
> > 
> > is it fixed ?
> 
> Yes, pull request [#128](https://github.com/FreeTubeApp/yt-channel-info/pull/128) has been merged

but when i try 
http://localhost:8000/getVideos?channelId=UCX8pnu3DYUnx8qy8V_c6oHg&sortBy=newst
or
http://localhost:8000/getVideos?channelId=@TechnoGamerzOfficial&sortBy=newst
i get error

**Comment by ChunkyProgrammer** [comment]
Set the version to 
`"yt-channel-info": "http://github.com/freetubeapp/yt-channel-info.git#1e80fc79bdc86355ca48425f03bc8a64d7451133"`

**Comment by krishtam-dev** [comment]
Yes i updated but it shows no items and null

**Comment by krishtam-dev** [comment]
solved Thanks 


and now error in getChannelVideosMore

AxiosError: Request failed with status code 400

**Comment by DoormatIka** [comment]
Has the issue been fixed on npm? It's not working with an npm install.
![image](https://user-images.githubusercontent.com/68234036/216083522-106c59b5-61b0-400d-bc67-4f4cb4d69b5c.png)
