### ISSUE TITLE
Get epoch time of upload

### ISSUE THREAD

**Issue by teakivy** [FreeTubeApp/yt-channel-info#13]
When using .getChannelVideos would it be possible to also return a numerical time of upload (for example, Epoch) as it tends to sometimes get older videos, which can break something getting the latest video (for example, im working on a discord bot to auto post uploads, that compares the video to the last video, if it has a different ID it will update, but if a video gets privated, or it returns an older video it will post that video aswell)

Sorry if this doesnt make sense, basically just return a numerical upload time

**Comment by bonesoul** [comment]
same question here, is this possible?

**Comment by absidue** [comment]
Hi unfortunately we aren't able to implement this, as the channel videos page only contains relative timestamps for the uploads, e.g. 4 hours ago, 2 days ago or 6 weeks ago. To get the exact timestamp you'll need to either use YouTube's official Data API (requires an account and has ratelimiting) or use something like [ytdl-core](https://github.com/fent/node-ytdl-core) to scrape the watch page for that video.
