### ISSUE TITLE
'Too many requests '

### ISSUE THREAD

**Issue by Ergo-proxy9847** [FreeTubeApp/yt-channel-info#21]
I was experimenting with the api and absent too many requests now I get a 429 error every time

Will this be okay later or will I permanently be unable to use the api?

**Comment by PrestonN** [comment]
It will go away over time, but there isn't much that can be done to prevent it. YouTube has a set amount a requests that you're allowed to make before you get blocked for a while. Using a proxy / VPN can help bypass it. Depending on what you're doing you may be able to use RSS to grab video feeds instead to save you some requests.

You'll have to keep this in mind when using the module and structure your code to handle this error as YouTube can change these limits in the future.
