### ISSUE TITLE
Cannot read property 'startTime' of undefined

### ISSUE THREAD

**Issue by thehungrycoder** [FreeTubeApp/yt-channel-info#30]
I'm seeing this error with a live video (while another live video is working fine). here is the stack trace

```
 Cannot read property 'startTime' of undefined
    at YoutubeGrabberHelper.parseVideo (/.../node_modules/yt-channel-info/app/helper.js:135:70)
    at /.../node_modules/yt-channel-info/app/helper.js:90:19
    at Array.map (<anonymous>)
    at YoutubeGrabberHelper.parseChannelVideoResponse (/.../node_modules/yt-channel-info/app/helper.js:89:8)
    at Function.getChannelVideosNewest (/.../node_modules/yt-channel-info/app/fetchers/channel.js:10:25)

```

I logged the `statusRenderer` object and this is what I see
```
{"text":{"runs":[{"text":"LIVE"}],"accessibility":{"accessibilityData":{"label":"LIVE"}}},"style":"LIVE","icon":{"iconType":"LIVE"}}
```
And in the video object, I don't see `upcomingEventData` property which is being used in line 135 (for `video.upcomingEventData.startTime`)

Any idea what could be wrong?

**Comment by GilgusMaximus** [comment]
Yes, looks like there might have been some changes or inconsistencies in determining the video type on a channel.
Could you send me a channel where it does not work?
Then I'd check it out and fix it

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Yes, looks like there might have been some changes or inconsistencies in determining the video type on a channel.
Could you send me a channel where it does not work?
Then I'd check it out and fix it

@thehungrycoder please provide a channel

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
