### ISSUE TITLE
Add option to specify proxy

### ISSUE THREAD

**Issue by bacnt2412** [FreeTubeApp/yt-channel-info#41]
I want to use proxy for country blocking channels

**Comment by GilgusMaximus** [comment]
At the moment proxies are not supported. You either have to use a VPN or a system wide proxy.

I am gonna transform this into a feature request. Should be easy to add, as something similar was done for another module already https://github.com/FreeTubeApp/yt-comment-scraper/pull/19

**Comment by GilgusMaximus** [comment]
Okay I added the option as a PR #42 
Could you download the source code of that PR (basically the master branch of my fork) and check whether the proxy option works? 
I do not have a proxy to test it and not much time at my hands at the moment to set one up.

If you confirm it works, I'll merge it and we will publish a new version
