### ISSUE TITLE
video.lengthSeconds returns 0 if the video is a Youtube short

### ISSUE THREAD

**Issue by mbg206** [FreeTubeApp/yt-channel-info#72]
when retrieving videos, if `durationText` is `'SHORTS'`, then `lengthSeconds` will return 0 instead of the actual video length in seconds.

**Comment by mbg206** [comment]
actually, after looking into the data that YouTube gives that is used by this library, I can see that YouTube doesn't give this information, and I see that this library will default this to 0 when this happens.

**Comment by ChunkyProgrammer** [comment]
Fixed in #75
